### ISSUE TITLE
mean_std.mat 

### ISSUE THREAD

**Issue by aligoglos** [arangesh/GPCycleGAN#1]
Please upload `mean_std.mat `
thanks.

**Comment by arangesh** [comment]
Which dataset are you referring to? I just confirmed that we have provided `mean_std.mat` files for LISA Gaze Dataset v0, LISA Gaze Dataset v1, and LISA Gaze Dataset v2. 

I would suggest downloading the dataset again and confirming this.

**Comment by aligoglos** [comment]
Thanks I downloaded `LISA Gaze Dataset v2` and found it.
